return {
	Left = { Enum.KeyCode.A, Enum.KeyCode.Q, Enum.KeyCode.Left, Enum.KeyCode.DPadLeft },
	Right = { Enum.KeyCode.D, Enum.KeyCode.Right, Enum.KeyCode.DPadRight },
	Jump = { Enum.KeyCode.Space, Enum.KeyCode.DPadUp, Enum.KeyCode.ButtonA },
	Crouch = { Enum.KeyCode.S, Enum.KeyCode.Down, Enum.KeyCode.DPadDown },
	Dash = { Enum.KeyCode.LeftShift, Enum.KeyCode.RightShift, Enum.KeyCode.ButtonR2 },
	Reset = { Enum.KeyCode.R, Enum.KeyCode.ButtonY },
	Deadzone = 0.18,
}
